import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";

test("DS failure log page exposes repair states and failure reasons", async () => {
  const [source, monitor, platformApi, styles] = await Promise.all([
    fs.readFile(new URL("../web/src/views/ds-failure-logs.js", import.meta.url), "utf8"),
    fs.readFile(new URL("../src/ds-failure-log-monitor.mjs", import.meta.url), "utf8"),
    fs.readFile(new URL("../src/platform-api.mjs", import.meta.url), "utf8"),
    fs.readFile(new URL("../web/src/styles.css", import.meta.url), "utf8"),
  ]);
  assert.match(source, /DS 失败任务日志/);
  assert.match(source, /选择范围/);
  assert.match(source, /实际命中/);
  assert.match(source, /重跑结果/);
  assert.match(source, /buildRetryTaskRows/);
  assert.match(source, /无失败任务/);
  assert.match(source, /renderRetryTaskIdentity/);
  assert.match(source, /已自动修复/);
  assert.match(source, /修复中/);
  assert.match(source, /待修复/);
  assert.match(source, /失败原因/);
  assert.match(source, /工作流实例/);
  assert.doesNotMatch(source, /定位失败任务/);
  assert.match(source, /失败项目/);
  assert.match(source, /失败工作流/);
  assert.match(source, /失败任务/);
  assert.match(source, /出错 SQL/);
  assert.match(source, /\/api\/ds-failure-logs/);
  assert.match(source, /n8n失败重启监控/);
  assert.match(source, /Global-Intelligent-Alarm-Repair-Assistant/);
  assert.match(source, /最多重跑 3 次并观察 30 分钟/);
  assert.match(source, /n8n 处理规则/);
  assert.match(source, /观察超过 30 分钟，需负责人处理/);
  assert.match(source, /后续重跑结果/);
  assert.match(source, /尚未触发后续重跑/);
  assert.match(source, /data-scheduled-country-page/);
  assert.match(source, /4 \/ 页/);
  assert.match(source, /renderDateRangeFilter\("ds-failure"/);
  assert.match(source, /renderDateRangeFilter\("ds-scheduled"/);
  assert.match(source, /id="\$\{prefix\}-start-date" type="date"/);
  assert.match(source, /id="\$\{prefix\}-end-date" type="date"/);
  assert.match(source, /startDate=\$\{range\.startDate\}&endDate=\$\{range\.endDate\}/);
  assert.match(source, /按时间范围查看 n8n 失败重启任务/);
  assert.match(source, /定时失败任务重跑/);
  assert.match(source, /两个重跑模块共用负责人配置/);
  assert.match(source, /id="ds-notification-process-open"/);
  assert.match(source, /function renderNotificationProcessModal/);
  assert.match(source, /负责人私聊/);
  assert.match(source, /国家群发/);
  assert.match(source, /两个模块也会通过对应国家的 TV bot_id 群发/);
  assert.doesNotMatch(source, /定时失败任务重跑仍只私聊/);
  assert.match(source, /\/api\/ds-failure-retry\/notifications\?limit=300/);
  assert.match(source, /国家群聊 TV bot_id/);
  assert.match(source, /botIds/);
  assert.match(source, /groupChatIds/);
  assert.doesNotMatch(source, /n8n 失败重启项目范围/);
  assert.doesNotMatch(source, /n8n 项目识别/);
  assert.doesNotMatch(source, /data-scheduled-project/);
  assert.doesNotMatch(source, /ds-n8n-scope-save/);
  assert.match(source, /data-ds-failure-tab="scheduled"/);
  assert.match(source, /\/api\/ds-scheduled-failure-watch/);
  assert.match(source, /DS调度监控/);
  assert.match(source, /重新查询/);
  assert.match(source, /尚未查询/);
  assert.doesNotMatch(styles, /\.ds-n8n-scope-/);
  assert.match(source, /function renderDateRangeFilter/);
  assert.match(source, /时间筛选/);
  assert.match(source, /data-scheduled-country-toggle/);
  assert.match(source, /scheduledCollapsedCountries/);
  assert.match(source, /aria-expanded=/);
  assert.match(styles, /\.ds-country-collapse-toggle/);
  assert.doesNotMatch(source, /\?date=/);
  assert.match(source, /renderDsFailureLogs\(root\) \{\s*syncAutoRefresh\(root\);\s*paint\(root\);\s*if \(!model\.retryControlLoaded\) refreshRetryPanel\(root\);\s*if \(!model\.scheduledConfigLoaded\) refreshScheduledConfig\(root\);\s*\}/);
  assert.doesNotMatch(source, /ds-country-choice/);
  assert.match(source, /\?country=/);
  assert.match(source, /Promise\.all\(selected\.map/);
  assert.match(source, /各国并行查询并在完成后立即显示/);
  assert.match(source, /renderCountryMultiSelect\("ds-failure-country"/);
  assert.match(source, /function renderCountryMultiSelect/);
  assert.match(source, /function bindCountryMultiSelect/);
  assert.match(source, /model\.retryCountries/);
  assert.doesNotMatch(source, /COUNTRY_QUERY_TIMEOUT_MS/);
  assert.match(source, /new AbortController\(\)/);
  assert.match(source, /id="ds-failure-stop-query"/);
  assert.match(source, /停止查询/);
  assert.match(source, /id="ds-failure-schedule-category"/);
  assert.match(source, /定时上线任务/);
  assert.match(source, /非定时上线任务/);
  assert.match(source, /失败节点尚未定位，可能为空跑，具体原因需人工确认/);
  assert.match(source, /function describeFailureReason/);
  assert.match(source, /英文报错，具体原因需人工确认/);
  assert.match(source, /AUTO_REFRESH_INTERVAL_MS = 60 \* 60 \* 1000/);
  assert.match(source, /SQL错误，需人工修改/);
  assert.match(source, /权限不足，需人工处理/);
  assert.match(source, /每轮最多提交一次重跑/);
  assert.match(source, /自动重跑中/);
  assert.match(source, /失败分类/);
  assert.match(source, /renderCountryMultiSelect\("ds-retry-country"/);
  assert.match(source, /id="ds-retry-toggle"[^>]+role="switch"/);
  assert.match(source, /ds-retry-header-actions/);
  assert.match(source, /role="switch" aria-checked=/);
  assert.match(source, /<select id="ds-retry-interval"/);
  assert.match(source, /\[60, 120, 240, 360\]/);
  assert.match(source, /id="ds-retry-minute"[^>]+min="0" max="59"/);
  assert.match(source, /COUNTRY_OPTIONS\.map\(\(item\) => item\.code\)/);
  assert.match(source, /停止立即测试/);
  assert.match(source, /manual_run_completed: "立即测试完成"/);
  assert.match(source, /\["control_disabled", "manual_run_stopped", "safety_stopped", "retry_stopped"\]/);
  assert.ok(source.indexOf("const selectedIntervalMinutes") < source.indexOf("model.retryActionLoading = true"));
  assert.doesNotMatch(source, /id="ds-retry-start-at"/);
  assert.match(source, /重跑历史/);
  assert.match(source, /schedule-history-table ds-retry-history-table/);
  assert.match(source, /retryRunId=/);
  assert.match(source, /打开详情页/);
  assert.match(source, /重跑历史详情/);
  assert.match(source, /taskUnlocated && !filters\?\.n8n/);
  assert.match(source, /DS 失败任务补充查询/);
  assert.match(source, /\/api\/ds-n8n-failure-watch\/evidence/);
  assert.match(source, /function hydrateVisibleN8nEvidence/);
  assert.match(source, /正在补充查询 DS 失败节点/);
  assert.match(source, /function n8nRepairDisplayStatus/);
  assert.match(source, /n8n_recovered: \{ label: "已修复"/);
  assert.match(source, /n8n_unresolved: \{ label: "未修复"/);
  assert.match(source, /n8n_unknown: \{ label: "修复结果待确认"/);
  assert.match(platformApi, /enrichDsEvidence: false/);
  assert.match(platformApi, /async resolveN8nFailureEvidence/);
  assert.match(platformApi, /timeoutMs: 8_000/);
  assert.match(source, /不重跑项目配置/);
  assert.match(source, /data-retry-project-country/);
  assert.match(source, /立即运行测试/);
  assert.match(source, /events\.has\("manual_run"\)/);
  assert.match(source, /events\.has\("manual_run_stopped"\)/);
  assert.match(source, /自动重跑开关未改变/);
  assert.match(source, /在所设置的重跑分钟执行第一轮，之后按所选间隔运行/);
  assert.match(source, /renderRetryLogDetail/);
  assert.match(source, /function formatRetryMessage/);
  assert.match(source, /timeZone: "Asia\/Shanghai"/);
  assert.match(source, /function failureReasonForDisplay/);
  assert.match(source, /const stopped = \["STOP", "STOPPED", "KILL", "5", "9"\]/);
  assert.match(source, /失败节点尚未定位，可能为空跑，具体原因需人工确认/);
  assert.match(styles, /\.ds-failure-retry-control \.ds-failure-filter-grid \{[\s\S]*grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)/);
  assert.match(source, /返回失败任务日志/);
  assert.match(source, /buildRetryRuns/);
  assert.match(source, /historyLogs = ordered\.filter\(\(item\) => item\.event !== "excluded"\)/);
  assert.match(source, /\["manual_run_completed", "scheduled_run_completed"\]\.includes\(item\.event\)/);
  assert.match(source, /wasRunning && !model\.retryControl\.manualRunning/);
  assert.match(source, /apiGet\("\/api\/ds-failure-retry\/logs\?limit=200"\)/);
  assert.match(source, /data-delete-retry-run/);
  assert.match(source, /<svg viewBox="0 0 24 24"/);
  assert.match(styles, /\.ds-retry-history-table \.danger-icon \{[\s\S]*border: 0;[\s\S]*background: transparent;/);
  assert.match(styles, /\.ds-retry-history-table \{ overflow: visible; \}/);
  assert.match(source, /apiDelete\("\/api\/ds-failure-retry\/logs"/);
  assert.match(source, /<th>运行时间<\/th><th>状态<\/th><th>国家<\/th><th>任务<\/th><th>重跑次数<\/th><th>结果<\/th><th>明细<\/th><th>删除<\/th>/);
  assert.match(source, /retryLogBadge/);
  assert.match(source, /repairStatus === "unresolved"/);
  assert.match(source, /每隔 1 小时自动重新查询当前国家/);
  assert.match(source, /查看节点日志/);
  assert.match(source, /工作流状态为失败或停止/);
  assert.match(monitor, /const defaultTargetDate = todayInTimeZone\(timeZone, now\)/);
  assert.match(monitor, /dateMode: explicitRange \? "explicit-date-range"/);
  assert.match(monitor, /dateMode: "country-local-lookback"/);
  assert.match(monitor, /PROJECT_QUERY_CONCURRENCY = 4/);
  assert.match(monitor, /FAILURE_ENRICH_CONCURRENCY = 3/);
  assert.match(monitor, /ORIGINAL_FAILURE_CACHE_TTL_MS = 90_000/);
  assert.match(monitor, /originalFailureInFlight\.has\(cacheKey\)/);
  assert.match(monitor, /normalizeLookbackDays\(requestedLookbackDays, 7\)/);
  assert.match(monitor, /mapWithConcurrency\(projects, PROJECT_QUERY_CONCURRENCY/);
  assert.match(monitor, /"list_instances"/);
  assert.match(monitor, /state_type: ""/);
  assert.match(monitor, /START_FAILURE_TASK_PROCESS/);
  assert.match(monitor, /runTimes/);
  assert.match(monitor, /"list_task_instances"/);
  assert.match(monitor, /"get_task_log"/);
  assert.match(monitor, /"extract_task_runtime_config"/);
  assert.match(monitor, /自动重试 1 次/);
  assert.doesNotMatch(monitor, /人工停止或终止，不自动重跑/);
  assert.doesNotMatch(monitor, /failure_policy: "scheduled_today_final_failure"/);
  assert.match(platformApi, /getDsFailureLogs\(filters = \{\}\)/);
  assert.match(platformApi, /countries: country \|\| undefined/);
  assert.doesNotMatch(platformApi, /dsAutoRetryManager\?\.decorate/);
  assert.match(platformApi, /return inspectDsFailureLogs/);
});

test("sidebar and server expose the independent DS failure log module", async () => {
  const [app, server] = await Promise.all([
    fs.readFile(new URL("../web/src/app.js", import.meta.url), "utf8"),
    fs.readFile(new URL("../src/server.mjs", import.meta.url), "utf8"),
  ]);
  assert.match(app, /path: "\/ds-failure-logs", label: "DS失败任务日志"/);
  assert.match(app, /function routeRenderKey\(route\)/);
  assert.match(app, /renderedRoute === routeKey/);
  assert.match(server, /url\.pathname === "\/api\/ds-failure-logs"/);
  assert.match(server, /url\.pathname === "\/api\/ds-failure-retry\/start"/);
  assert.match(server, /url\.pathname === "\/api\/ds-failure-retry\/config"/);
  assert.match(server, /url\.pathname === "\/api\/ds-failure-retry\/run-now"/);
  assert.match(server, /url\.pathname === "\/api\/ds-failure-retry\/run-now\/stop"/);
  assert.match(server, /url\.pathname === "\/api\/ds-failure-retry\/logs"/);
  assert.match(server, /url\.pathname === "\/api\/ds-failure-retry\/notifications"/);
  assert.match(server, /method === "DELETE" && url\.pathname === "\/api\/ds-failure-retry\/logs"/);
});
